### ISSUE TITLE
User Interface Epic

### ISSUE THREAD

**Issue by jhrr** [ocp/DALME-Online-Database#1]
# User Interface Epic

A ticket collating everything that needs to be done to bring the new v2 user interface up to spec for production release.

- [ ] Triage these issues into topics/zones/categories.
- [ ] `Agent` data and schema are out of sync on the UI.
- [ ] The `updatePreferences` subscription fires multiple times when logging in to the UI.
- [ ] State machines are mostly refactored to be compliant with xstate v5, but there are certain details that still need alterations, eg. `internal = true` is no longer meaningful syntax. 
- [ ] Login modal spinner (on button click) is not showing.
- [ ] The `requests.sets` payloads don't exist anymore, the set schemas still exist.
- [ ] Record loading is very slow (on the `Records` tab).
- [ ] Do we also need a wactcher than resubmits any requests in the queue when we transition from `reauthenticate` -> `authorized`?
- [ ] Might need a callback action for the authorization code rather than a `fromPromise` action.
