### ISSUE TITLE
DALME V2/IDA Beta Launch Epic

### ISSUE THREAD

**Issue by jhrr** [ocp/DALME-Online-Database#5]
Ticket for collecting everything that need resolution before V2 can be launched as a beta deployment.

- [ ] https://github.com/ocp/DALME-Online-Database/issues/4
- [ ] Create groups and users for Global Pharmacopeias in the staging environment.
  - [x] ~Any current user assigned to the primary group "Team Pharmacopeia" should be moved to Global Pharmacopeias.~
  - [ ] We might need to reassign all `Group` permissions manually if we don't incorporate it into the data migration (@jhrr skipped it to make progress elsewhere but will revisit ASAP.)
- [ ] Setup Sentry (or similar, we should evaluate some competitors) for staging monitoring.
  - [ ] Whichever service we go with can we get an OSS plan?
  - [ ] eg. https://sentry.io/for/open-source/

**Comment by jhrr** [comment]
Closing as stale.
